export const ADD_TODO = "TODOS/ADD_TODO";
export const REMOVE_TODO ='TODOS/REMOVE_TODO';
export const TOGGLE_TODO ='TODOS/TOGGLE_TODO';
export const TOGGLE_ALL_TODO ='TODOS/TOGGLE_ALL_TODO';
export const CLEAR_COMPLETED_TODO ='TODOS/CLEAR_COMPLETED_TODO';
export const EDIT_TODO ='TODOS/EDIT_TODO';